### ISSUE TITLE
The W for WebSub should not be the W for Web.

### ISSUE THREAD

**Issue by Zegnat** [sebilasse/indieweb-origami#1]
For WebSub the exact same W is used as for IndieWebCamp and Homebrew Website Club. The W in those two logos is clearly used to mean the internet or websites. Using it again for a specific building block feels like we are overloading the letter shape.

“IWC: that W is the WebSub logo, but what are the other things?!”

**Comment by sebilasse** [comment]
Will probably do tomorrow.

**Comment by sebilasse** [comment]
Not sure. See https://github.com/sebilasse/indieweb-origami/blob/master/CI.pdf

**Comment by sebilasse** [comment]
Closing for now as the W is no distinct ...
