### ISSUE TITLE
IndieAuth poster describes RelMeAuth

### ISSUE THREAD

**Issue by Zegnat** [sebilasse/indieweb-origami#11]
This:

> It works by linking your website to one or more authentication providers such as Twitter or GitHub, then entering your domain name in the login form on websites that support IndieAuth

And this:

> Add links on your home page to your external social profiles with the attribute [rel="me"]. Ensure your external profiles link back to your home page.

Describe how [RelMeAuth](https://indieweb.org/RelMeAuth) works.

[IndieAuth](https://indieweb.org/IndieAuth) only defines how an authorization endpoint works and how it communicates with a token endpoint.

This makes me think the poster should really be about [Web sign-in](https://indieweb.org/Web_sign-in). Web sign-in can be RelMeAuth or IndieAuth or any other system that allows authentication through a homepage URL. Web sign-in can use IndieAuth.com (which will be [renamed to indielogin](https://chat.indieweb.org/meta/2017-07-19/1500481059573000) (scope [described here](https://chat.indieweb.org/meta/2017-07-19/1500481422110000)).) to support both RelMeAuth and IndieAuth at once, but that is an implementation detail.

**Comment by sebilasse** [comment]
@Zegnat The confusion clearly came from the wiki 
Please see the "How To" Section in
https://indieweb.org/IndieAuth

This must change as well.

**Comment by Zegnat** [comment]
> <i>[The wiki]</i> must change as well.


Yes.

There was some discussion about changing the how to, see [the issue filed on that same page](https://indieweb.org/IndieAuth#how_to_should_include_endpoint_definition). My draft version of the IndieAuth page includes [an updated section](https://indieweb.org/User:Vanderven.se_martijn/IndieAuth#Set_up_using_IndieAuth.com). I should probably go and take that section from the draft page and put it on the “real” page.
