### ISSUE TITLE
Homebrew Website Club is not one word.

### ISSUE THREAD

**Issue by Zegnat** [sebilasse/indieweb-origami#5]
On the IWC poster:

* It is right on the logo at the top.
* It is wrong (written as one word) on the summary at the bottom.

See [/IndieWebCamps](https://indieweb.org/IndieWebCamps) for canonical spellings, emphasis mine:

> <i>[…]</i> IndieWeb related events (**IndieWebCamps**, **Homebrew Website Club**, **IndieWeb** talks at conferences etc.)

**Comment by sebilasse** [comment]
will be fixed in the next commit

**Comment by sebilasse** [comment]
Fixed. See https://github.com/sebilasse/indieweb-origami/blob/master/Poster/_PDF/IWC.pdf
