### ISSUE TITLE
Why tag Webmention in a description of Micropub?

### ISSUE THREAD

**Issue by Zegnat** [sebilasse/indieweb-origami#6]
Current copy on the Micropub flyer:

> You tell a story in Syria and submit it to NYT. Some editors review or enrich the material and publish it to their public channels. Readers can reply with a comment which is published on their pages too. Then Webmention notifies the author and the comment about the permalink.

Does that last sentence really add anything? What do Webmentions matter in this context?

**Comment by sebilasse** [comment]
Removed sentence. See upcoming commit ...

**Comment by sebilasse** [comment]
Fixed in 
https://github.com/sebilasse/indieweb-origami/blob/master/Poster/_PDF/MICROPUB.pdf
