### ISSUE TITLE
Feature how Micropub lets you use many tools, even at the same time.

### ISSUE THREAD

**Issue by Zegnat** [sebilasse/indieweb-origami#7]
I think one of the powers of Micropub is to have a normalised API for your own site that can be used by any application. Maybe it should highlight how you can use different clients to post different things?

Quill is great for posts, but there are also specialised things like [Screech](https://indieweb.org/Screech) for audio posts, or services like [OwnYourGram](https://indieweb.org/OwnYourGram). Thanks to [micro.blog](https://indieweb.org/micro.blog#Apps) we are also getting mobile apps. All of these will instantly work if a website has a Micropub endpoint.

**Comment by sebilasse** [comment]
Done. See 
https://github.com/sebilasse/indieweb-origami/blob/master/Poster/_PDF/MICROFORMATS.pdf
